services:
  postgres:
    image: postgres:16-alpine
    container_name: financeiro-pessoal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: financeiro_db
      POSTGRES_USER: financeiro
      POSTGRES_PASSWORD: financeiro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
